# Generated by Django 4.1.7 on 2023-02-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
